### ISSUE TITLE
uniqueFileName not respected when calling Storage.disk(...)

### ISSUE THREAD

**Issue by davidzwa** [googlicius/file-storage#10]
> uniqueFileName not respected when calling Storage.disk(...)

When setting the uniqueFileName global to true:
```
    Storage.config<BuiltInDiskConfig>({
      uniqueFileName: true,
      defaultDiskName: 'local',
      diskConfigs: [
        {
          driver: DriverName.LOCAL,
          name: 'local',
          root: 'media'
        }
      ]
    });
```

The internal default disk works fine, we get the unique file with extension `.txt`:
```
    await Storage.put(Buffer.from("I am a unique one."), "asd.txt");
```

However, when calling the disk getter, the setting is not applied:
```
   await Storage.disk('local').put(Buffer.from("I will overwrite asd.txt"), "asd.txt");
```

Could be an easy fix!

**Comment by davidzwa** [comment]
From my understand the specific driver does not have any awareness of the setting that the StorageClass global is equipped with:

https://github.com/googlicius/file-storage/blob/4d470e71a9a24b7acc0d6f82ac536dacfdd19a4d/packages/core/lib/file-storage.ts#L191

The LocalDriver:
https://github.com/googlicius/file-storage/blob/4d470e71a9a24b7acc0d6f82ac536dacfdd19a4d/packages/local-driver/lib/local-driver.ts#L72

As there is a Driver implementation which the Storage constructs for us, I think we could give it a SettingsContext class (fitting your design). An even more nice design (without Dependency Injection) would be a context factory to provide the settings context from our own system, so settings can be adjusted on the fly (or per file/folder/storage).

What do you think?

**Comment by googlicius** [comment]
Hi @davidzwa, Yes it's expected.

But the second param of function `Storage.disk` allows to get an instance of StorageClass with specific disk, so I think it will be fit with your needs.

My expectation is keep the usage as much as simple, beside the global setup, I think we can initialize StorageClass instance for specific disk with it own settings, like the way aws-sdk implemented.
