### ISSUE TITLE
Importing the default doesn't work when using ES2022 modules

### ISSUE THREAD

**Issue by sr258** [googlicius/file-storage#11]
I'm working on an application that uses ES2022 modules. So I've set `"type": "module"` in `package.json` and the TypeScript settings are `"target": "ES2022", "module": "ES2022"`.

I'm experiencing the following issue:

When I import the Storage class like this and run it I get an error:
```ts
import Storage from '@file-storage/core';
Storage.config({});
```

Error:
```
Storage.config({});
        ^
TypeError: Storage.config is not a function
```

There are currently two workaround I have found:

- I can turn off typechecking and call `(Storage as any).default.config({});`
- I can import the Storage class like this: `import { Storage } from '@file-storage/core/dist/file-storage.js';`

It's also possible to get a proper import by downgrading the whole application to CommonJS module (remove `"type": "module"` from `package.json` and set `"module": "CommonJS"` in `tsconfig.json`), but I can't do that as other packages only work in a ESNext module.

I've created a minimal sample to reproduce the issue: https://github.com/sr258/file-storage-minimal-sample

Steps to reproduce:

- Clone the repo
- `npm install`
- `npm build`
- `npm run start:error`

It looks like way the class is exported doesn't work with a fully ES2022 module.

**Comment by sr258** [comment]
I think a possible solution might be to create a hybrid module that includes ESM and CommonJS: https://www.sensedeep.com/blog/posts/2021/how-to-create-single-source-npm-module.html

Moving to ESM makes sense anyway to be future-proof.

**Comment by sr258** [comment]
I've given the hybrid module a try: https://github.com/sr258/file-storage

The hybrid build works in general, but I've encountered two issues

- Local imports in modules must have '.js' at the end. I've changed the imports in my fork like this, but I'm not sure if it will break the CommonJS version
- The code uses `require` inside code and an ESM module doesn't allow that. That's why the packages don't work in my fork. Moving to dynamic `import` would require making the function async.

Before I put more work into this, I'd like to know if you are interested in creating a hybrid package.

**Comment by googlicius** [comment]
Hi @sr258 , thanks for interesting my library, I'm not sure why your application use es2022 version, it's not safe when all Node.js applications I know use CommonJS, and many lirabries are not support Node.js ESM as well.

But anyway, making hybrid cause a lot of changes. I think another solution that we could create another build for ESM module, and the build output could be `dist/esm`. We just create a new tsconfig file like: `tsconfig-esm.build.json`. I'm not try it yet, and this library also use some another libraries so I'm not sure those are supporting ESM or not.

**Comment by sr258** [comment]
Some libraries are starting to move to pure ESM and if you want to use those, you have to use ESM in your own application as well.

The problem is that only another tsconfig file is not enough. As I mention above, the imports need to be different in a pure ESM module and you can't use require.

I think the underlying problem is that the TS typings and the default export that you need to use when importing in a ESM setup, don't match. It would be possible to use the current package if the typings included a "default" property.

**Comment by googlicius** [comment]
Removing `require` should be easy. 

And after read throught some articles about hybrid package, I have some another ideas that we could create another tsconfig for esm as I mentioned above and also update tsconfig, package.json,... in each package, so it ready to use either in ESM or CommonJS application.

This article is very good guide to do it: https://dev.to/mbarzeev/hybrid-npm-package-through-typescript-compiler-tsc-150c

And no need to update the source code as well.

**Comment by googlicius** [comment]
The library is now support ESM. One note about mandatory file extension in ESM, currently I don't add '.js' for every import, and also don't want it, so the best workaround is to add flag `--experimental-specifier-resolution=node` to make it resolve js files.

**Comment by sr258** [comment]
Thanks for working on this so quickly! The ESM import now works.

I'm still running into the issue that ESM requires '.js' for imports. The workaround with `--experimental-specifier-resolution=node` was already removed in Node 19: https://nodejs.org/en/blog/announcements/v19-release-announce/#custom-esm-resolution-adjustments

So in the long run, I think using the extensions is unavoidable.

**Comment by sr258** [comment]
I got it working with Node 19 and a custom ESM loader:

`esm-loader.js:`

```es6
// Based on: https://github.com/nodejs/loaders-test/tree/main/commonjs-extension-resolution-loader
// Only uses the CommonJS resolution style for imports starting with ./ or ../

import { isBuiltin } from 'node:module';
import { dirname } from 'node:path';
import { cwd } from 'node:process';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { promisify } from 'node:util';

import resolveCallback from 'resolve/async.js';

const resolveAsync = promisify(resolveCallback);

const baseURL = pathToFileURL(cwd() + '/').href;


export async function resolve(specifier, context, next) {
  const { parentURL = baseURL } = context;

  if (isBuiltin(specifier) || !(specifier.startsWith("./") || specifier.startsWith("../"))) {
    return next(specifier, context);
  }

  // `resolveAsync` works with paths, not URLs
  if (specifier.startsWith('file://')) {
    specifier = fileURLToPath(specifier);
  }
  const parentPath = fileURLToPath(parentURL);

  let url;
  try {
    const resolution = await resolveAsync(specifier, {
      basedir: dirname(parentPath),
      // For whatever reason, --experimental-specifier-resolution=node doesn't search for .mjs extensions
      // but it does search for index.mjs files within directories
      extensions: ['.js', '.json', '.node', '.mjs'],
    });
    url = pathToFileURL(resolution).href;
  } catch (error) {
    if (error.code === 'MODULE_NOT_FOUND') {
      // Match Node's error code
      error.code = 'ERR_MODULE_NOT_FOUND';
    }
    throw error;
  }

  return next(url, context);
}
```

Run Node 19 with:

`node --loader=./esm-loader.js index.js`
